services:

  user-service-db:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: user-service-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: plplpl123
      MYSQL_DATABASE: user-service
      MYSQL_USER: user-service
      MYSQL_PASSWORD: plplpl123
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
